---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    server: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
