apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trainee-clusterrole
rules:
  - apiGroups:
      - ""
    resources: [ "*" ]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources: [ "*" ]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources: [ "*" ]
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trainee-clusterrole-binging
subjects:
  - kind: User
    name: eks-admin-trainee
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: trainee-clusterrole
  apiGroup: rbac.authorization.k8s.io